### ISSUE TITLE
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union

### ISSUE THREAD

**Issue by jbaiter** [comfuture/function-schema#15]
When calling `get_function_schema` on the following function, the exception `TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union` is raised when `isinstance(none, T)` is called, where `T` is `"Annotated[str, Doc('The input prompt for the image')]"`.

The same thing happens when the annotation on the `str` is a string and not a `Doc` instance.

The function signature in question:

```python
    @tool("When a user wants you to generate an image, use this function.")
    async def generate_image(
        self, prompt: Annotated[str, Doc("The input prompt for the image")]
    ) -> tuple[
        Annotated[
            LLMResult, "The actual prompt that was used for generating the image"
        ],
        UserResult,
    ]: ...
```

`get_function_schema` is called on the method in the `@tool` decorator.

The problem seems to be that `T` in the library code is a `str` when this error happens, and not a type of some kind. This seemingly happens because `get_origin(param.annotation)` returns `None` in this case, which is why the `is_annotated` branch is not executed.

This is on CPython 3.12.

**Edit:** Found the cause, the module the method is defined in has `from __future__ import annotations`. In retrospect, this is expected, since this implicitely converts all annotations to strings, which is why I'm seeing the error. Removing the import fixes the issue. This issue should probably still be open, since [PEP563](https://peps.python.org/pep-0563/#) compatibility (i.e. parsing the strings from `__annotations__`) would be great for making this more compatible and future-proof. This would require rewriting the code to use [`typing.get_type_hints(func)`](https://docs.python.org/3/library/typing.html#typing.get_type_hints) instead of `get_args` and `get_origin` (as per the ["Backwards Compatibility"](https://peps.python.org/pep-0563/#backwards-compatibility) section in the PEP.)

**Comment by comfuture** [comment]
@jbaiter Thank you for discovering and fixing a compatibility issue that I almost missed. I will soon review and merge the pull request.
